-- 코드를 입력하세요
SELECT 
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR,
    COUNT(*)
FROM ANIMAL_OUTS
GROUP BY TO_NUMBER(TO_CHAR(DATETIME, 'HH24'))
HAVING TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) <= 19 AND TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) >= 9
ORDER BY HOUR ASC